-- Desde System
CREATE ROLE ADMINISTRADOR_DBA;
-- GRANT SELECT ANY TABLE WITH GRANT OPTION TO ADMINISTRADOR_DBA;
GRANT CREATE ANY INDEX TO ADMINISTRADOR_DBA;
GRANT CREATE PUBLIC SYNONYM TO ADMINISTRADOR_DBA;
GRANT CREATE ANY TABLE TO ADMINISTRADOR_DBA;
GRANT CREATE ANY VIEW TO ADMINISTRADOR_DBA;
GRANT ALTER ANY INDEX TO ADMINISTRADOR_DBA;
GRANT ALTER ANY TABLE TO ADMINISTRADOR_DBA;
GRANT DROP ANY INDEX TO ADMINISTRADOR_DBA;
GRANT DROP ANY SYNONYM TO ADMINISTRADOR_DBA;
GRANT DROP PUBLIC SYNONYM TO ADMINISTRADOR_DBA;
GRANT DROP ANY VIEW TO ADMINISTRADOR_DBA;
GRANT ALTER SESSION TO ADMINISTRADOR_DBA;
GRANT CREATE PROFILE TO ADMINISTRADOR_DBA;
GRANT CREATE ROLE TO ADMINISTRADOR_DBA;
GRANT CREATE ROLLBACK SEGMENT TO ADMINISTRADOR_DBA;
GRANT ALTER TABLESPACE TO ADMINISTRADOR_DBA;
GRANT ALTER USER TO ADMINISTRADOR_DBA;
GRANT DROP PROFILE TO ADMINISTRADOR_DBA;
GRANT DROP ROLLBACK SEGMENT TO ADMINISTRADOR_DBA;
GRANT DROP TABLESPACE TO ADMINISTRADOR_DBA;
GRANT DROP USER TO ADMINISTRADOR_DBA;
GRANT ALTER DATABASE TO ADMINISTRADOR_DBA;
GRANT UNLIMITED TABLESPACE TO ADMINISTRADOR_DBA;
GRANT CREATE TABLESPACE TO ADMINISTRADOR_DBA;
---

--
GRANT SELECT ANY TABLE TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO ADMINISTRADOR_DBA;

GRANT CREATE USER TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO ADMINISTRADOR_DBA;


GRANT CREATE PUBLIC SYNONYM TO ADMINISTRADOR_DBA;
GRANT SELECT ON dba_objects TO ADMINISTRADOR_DBA;
GRANT CONNECT TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
CREATE USER ADMINISTRADOR_DB IDENTIFIED BY ADMINISTRADOR_DB DEFAULT TABLESPACE ts_apoyoalimentario_def QUOTA 50M ON ts_apoyoalimentario_def;
GRANT ADMINISTRADOR_DBA TO ADMINISTRADOR_DB;

GRANT SELECT ON dba_sys_privs TO ADMINISTRADOR_DB WITH GRANT OPTION;
GRANT SELECT ON dba_role_privs TO ADMINISTRADOR_DB WITH GRANT OPTION;
GRANT SELECT ON dba_users TO ADMINISTRADOR_DB WITH GRANT OPTION;
GRANT CREATE PUBLIC SYNONYM TO ADMINISTRADOR_DBA;
GRANT SELECT ON dba_objects TO ADMINISTRADOR_DB;
grant select on dba_tab_privs to administrador_db;

GRANT CONNECT TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT ADMINISTRADOR_DBA TO ADMINISTRADOR_DB;
