conn administrador_db/ADMINISTRADOR_DB;

CREATE SEQUENCE incremento_id_convocatoria
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE incremento_id_cuposconv
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE incremento_id_solicitud
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE incremento_id_soporte
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE incremento_k_idsoldia
INCREMENT BY 1
START WITH 1;
