CREATE SEQUENCE incremento_id_his_solicitud
INCREMENT BY 1
START WITH 1;
CREATE PUBLIC SYNONYM incremento_id_his_solicitud FOR ADMINISTRADOR_DB.incremento_id_his_solicitud;

GRANT SELECT ON SOPORTE TO ADMIN_APOYO;

CREATE SEQUENCE incremento_k_id_benef
INCREMENT BY 1
START WITH 1;
CREATE PUBLIC SYNONYM incremento_k_id_benef FOR ADMINISTRADOR_DB.incremento_k_id_benef;

CREATE SEQUENCE incremento_k_idbenefdia
INCREMENT BY 1
START WITH 1;
CREATE PUBLIC SYNONYM incremento_k_idbenefdia FOR ADMINISTRADOR_DB.incremento_k_idbenefdia;

CONN SYSTEM/12345;

GRANT CREATE PROCEDURE TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT ALTER ANY PROCEDURE TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO ADMINISTRADOR_DBA WITH ADMIN OPTION;

GRANT CREATE TRIGGER TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
----------------------------------------------------------
GRANT CREATE ANY DIRECTORY TO ADMINISTRADOR_DBA WITH ADMIN OPTION;

CONN ADMINISTRADOR_DB/ADMINISTRADOR_DB
CREATE OR REPLACE DIRECTORY PDF AS '/home/skamilo11/Descargas/pdf';

connect sys as sysdba
12345
GRANT EXECUTE ON UTL_FILE TO ADMINISTRADOR_DBA;
GRANT EXECUTE ON UTL_FILE TO ADMINISTRADOR_DB;
GRANT EXECUTE ON UTL_FILE TO ADMIN_APOYO;

CONN ADMINISTRADOR_DB/ADMINISTRADOR_DB
grant  read, write on directory PDF to sys;
--chmod -R 777 /home/skamilo11/Descargas/pdf

ALTER TABLE  Solicitud
DROP CONSTRAINT CK_I_ESTADOSOL;

ALTER TABLE  Solicitud
ADD CONSTRAINT CK_I_ESTADOSOL CHECK (I_ESTADOSOL in ('R','C','P','A','S'));

ALTER TABLE  HistoricoSolicitud
DROP CONSTRAINT CK_ESTADOHIST;

ALTER TABLE  HistoricoSolicitud
ADD CONSTRAINT CK_ESTADOHIST CHECK (I_ESTADOHIST in ('R','C','P','A','S'));

GRANT SELECT,INSERT ON HISTORICOSOLICITUD TO ADMIN_APOYO;
GRANT EXECUTE ON PK_APOYO_ALIMENTARIO TO ADMIN_APOYO;
CREATE PUBLIC SYNONYM PK_APOYO_ALIMENTARIO FOR ADMINISTRADOR_DB.PK_APOYO_ALIMENTARIO;

CREATE PUBLIC SYNONYM AS_PDF_MINI FOR ADMINISTRADOR_DB.AS_PDF_MINI;
GRANT EXECUTE ON AS_PDF_MINI TO ADMIN_APOYO;

------------------------------------
ALTER TABLE  Convocatoria
 DROP CONSTRAINT CK_I_ESTADOCONV;

ALTER TABLE  Convocatoria
 ADD CONSTRAINT CK_I_ESTADOCONV CHECK (I_ESTADOCONV in ('A','D','S','B','P','C'));
 /**
  * A abierta
  * D cancelada
  * S asignando puntaje
  * B asignando beneficio
  * P Pendiente por publicación
  * C Cerrada
  */
CREATE PUBLIC SYNONYM Auditoria FOR ADMINISTRADOR_DB.Auditoria;
CREATE SEQUENCE incremento_k_auditoria
INCREMENT BY 1
START WITH 1;
CREATE PUBLIC SYNONYM incremento_k_auditoria FOR ADMINISTRADOR_DB.incremento_k_auditoria;
