CREATE SEQUENCE incremento_id_his_solicitud
INCREMENT BY 1
START WITH 1;
CREATE PUBLIC SYNONYM incremento_id_his_solicitud FOR ADMINISTRADOR_DB.incremento_id_his_solicitud;

GRANT SELECT ON SOPORTE TO ADMIN_APOYO;

CREATE SEQUENCE incremento_k_id_benef
INCREMENT BY 1
START WITH 1;
CREATE PUBLIC SYNONYM incremento_k_id_benef FOR ADMINISTRADOR_DB.incremento_k_id_benef;

CREATE SEQUENCE incremento_k_idbenefdia
INCREMENT BY 1
START WITH 1;
CREATE PUBLIC SYNONYM incremento_k_idbenefdia FOR ADMINISTRADOR_DB.incremento_k_idbenefdia;

CONN SYSTEM/12345;

GRANT CREATE PROCEDURE TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT ALTER ANY PROCEDURE TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO ADMINISTRADOR_DBA WITH ADMIN OPTION;

GRANT CREATE TRIGGER TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO ADMINISTRADOR_DBA WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO ADMINISTRADOR_DBA WITH ADMIN OPTION;

CONN ADMINISTRADOR_DB/ADMINISTRADOR_DB
