CONNECT ADMINISTRADOR_DB/ADMINISTRADOR_DB;
-- USUARIO CREADOR_ESTUDIANTE
CREATE USER CREADOR_ESTUDIANTE IDENTIFIED BY CREADOR_ESTUDIANTE;
GRANT CONNECT, MANEJADOR_USUARIO_ESTUDIANTE TO CREADOR_ESTUDIANTE;

--USUARIO ADMINISTRADOR_BIENESTAR
CREATE USER ADMINISTRADOR_BIENESTAR IDENTIFIED BY ADMINISTRADOR_BIENESTAR;
GRANT CONNECT, ADMIN_APOYO, MANEJADOR_USUARIO_ADMIN, REVISOR_SERV_SOCIAL, REVISOR_SOLICITUD, REVISOR_ASISTENCIA TO ADMINISTRADOR_BIENESTAR;

--USUARIOS ASISTTENTE_BIENESTAR
CREATE USER ASISTENTE_BIENESTAR IDENTIFIED BY ASISTENTE_BIENESTAR;
GRANT CONNECT, REVISOR_SOLICITUD, REVISOR_SERV_SOCIAL TO ASISTENTE_BIENESTAR;


--USUARIO USU_ESTUDIANTE
--CREATE USER USU_ESTUDIANTE OD;
--GRANT CONNECT,ROLE_ESTUDIANTE TO USU_ESTUDIANTE;

--USUARIO USU_DESARROLLADOR
CREATE USER USU_DESARROLLADOR IDENTIFIED BY USU_DESARROLLADOR;
GRANT CONNECT, ROLE_DESARROLLADOR TO USU_DESARROLLADOR;


-- Nuevos usuarios
--Administrado ADMIN_APOYO
CREATE USER U55054789 IDENTIFIED BY U55054789;
GRANT ADMIN_APOYO,CONNECT,MANEJADOR_USUARIO_ADMIN,REVISOR_SOLICITUD,REVISOR_SERV_SOCIAL,REVISOR_ASISTENCIA TO U55054789;
--CREATE USER U54068977 IDENTIFIED BY U54068977;
--CREATE USER U55471632 IDENTIFIED BY U55471632;

--Estudiante
CREATE USER U20112020048 IDENTIFIED BY U20112020048;
GRANT CONNECT,ROLE_ESTUDIANTE TO U20112020048;

CREATE USER U20121020099 IDENTIFIED BY U20121020099;
GRANT CONNECT,ROLE_ESTUDIANTE TO U20121020099;
