DROP ROLE MANEJADOR_USUARIO_ESTUDIANTE;
DROP ROLE MANEJADOR_USUARIO_ADMIN;
DROP ROLE ADMIN_APOYO;
DROP ROLE REVISOR_SOLICITUD;
DROP ROLE REVISOR_SERV_SOCIAL;
DROP ROLE REVISOR_ASISTENCIA;
DROP ROLE ROLE_ESTUDIANTE;
DROP ROLE ROLE_DESARROLLADOR;
